apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

source:
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetRevision: 55.5.0
  helm:
    skipCrds: true
    values: |
      grafana:
        enabled: true
        adminPassword: admin
        service:
          type: NodePort
          nodePort: 32000

        defaultDashboardsEnabled: true

        additionalDataSources:
          - name: Prometheus
            type: prometheus
            url: http://monitoring-kube-prometheus-prometheus.monitoring:9090
            access: proxy
            isDefault: true

